# Generated by Django 4.0 on 2021-12-14 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
