# Generated by Django 3.2.7 on 2021-11-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_photo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
